# Generated by Django 4.2.5 on 2023-11-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysilant', '0002_car_machine_components_service_company_maintenance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_company',
            old_name='company',
            new_name='name',
        ),
    ]
